name: get AML SDK python package list

on:
  workflow_dispatch:

jobs:
  list-endpoints:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: before install
        run: |
          pip list

      # 3. Install Azure ML SDK and dependencies
      - name: Install Azure ML SDK
        run: |
          pip install azure-ai-ml azure-identity

      - name: after install
        run: |
          pip list

      - name: python version
        run: |
          python -V
